### ISSUE TITLE
Incorrect code in Chapter 2

### ISSUE THREAD

**Issue by vuduclyunitn** [PacktPublishing/Hands-On-Web-Scraping-with-Python#1]
I found this snippet of code is incorrect.
1. >>> import urllib.request
2. >>> someRequest = urllib.request.urlopen(URL) #load/Open the URL
3. >>> urllib.request.getheaders() #Lists all HTTP headers. 
4. >>> urllib.request.getheader("Content-Type") #return value of header 'Content-Type''text/html; charset=ISO-8859-1' or 'utf-8'

Line 3 and 4 must be
someRequest.request.getheaders() and someRequest.request.getheader("Content-Type")

**Comment by packt-pradeeps** [comment]
Hi @vuduclyunitn 

You are right, the correct code is as follows:

**import urllib.request
url='https://www.samsclub.com/sitemap.xml'
someRequest = urllib.request.urlopen(url)#loads provided URL
someRequest.getheaders() #Lists all HTTP headers.
someRequest.getheader("Content-Type") #return value of header 'Content-Type'** 

The output can be seen in the following image:
![urllib_http_header_output](https://user-images.githubusercontent.com/45961039/89759415-c257a800-db07-11ea-96d5-c48f5156a081.jpg)
